export type SystemColor = 
    | 'primary'
    | 'on-primary'
    | 'primary-container'
    | 'on-primary-container'
    | 'secondary'
    | 'on-secondary'
    | 'secondary-container'
    | 'on-secondary-container'
    | 'tertiary'
    | 'on-tertiary'
    | 'tertiary-container'
    | 'on-tertiary-container'
    | 'error'
    | 'on-error'
    | 'error-container'
    | 'on-error-container'
    | 'primary-fixed'
    | 'primary-fixed-dim'
    | 'on-primary-fixed'
    | 'on-primary-fixed-variant'
    | 'secondary-fixed'
    | 'secondary-fixed-dim'
    | 'on-secondary-fixed'
    | 'on-secondary-fixed-variant'
    | 'tertiary-fixed'
    | 'tertiary-fixed-dim'
    | 'on-tertiary-fixed'
    | 'on-tertiary-fixed-variant'
    | 'surface-dim'
    | 'surface'
    | 'surface-bright'
    | 'surface-container-lowest'
    | 'surface-container-low'
    | 'surface-container'
    | 'surface-container-high'
    | 'surface-container-highest'
    | 'on-surface'
    | 'on-surface-variant'
    | 'outline'
    | 'outline-variant'
    | 'inverse-surface'
    | 'inverse-on-surface'
    | 'inverse-primary'
    | 'scrim'
    | 'shadow';

export const BG_SYSTEM_COLOR_MAP: Record<SystemColor, string> = {
    'primary': 'bg-primary',
    'on-primary': 'bg-on-primary',
    'primary-container': 'bg-primary-container',
    'on-primary-container': 'bg-on-primary-container',
    'secondary': 'bg-secondary',
    'on-secondary': 'bg-on-secondary',
    'secondary-container': 'bg-secondary-container',
    'on-secondary-container': 'bg-on-secondary-container',
    'tertiary': 'bg-tertiary',
    'on-tertiary': 'bg-on-tertiary',
    'tertiary-container': 'bg-tertiary-container',
    'on-tertiary-container': 'bg-on-tertiary-container',
    'error': 'bg-error',
    'on-error': 'bg-on-error',
    'error-container': 'bg-error-container',
    'on-error-container': 'bg-on-error-container',
    'primary-fixed': 'bg-primary-fixed',
    'primary-fixed-dim': 'bg-primary-fixed-dim',
    'on-primary-fixed': 'bg-on-primary-fixed',
    'on-primary-fixed-variant': 'bg-on-primary-fixed-variant',
    'secondary-fixed': 'bg-secondary-fixed',
    'secondary-fixed-dim': 'bg-secondary-fixed-dim',
    'on-secondary-fixed': 'bg-on-secondary-fixed',
    'on-secondary-fixed-variant': 'bg-on-secondary-fixed-variant',
    'tertiary-fixed': 'bg-tertiary-fixed',
    'tertiary-fixed-dim': 'bg-tertiary-fixed-dim',
    'on-tertiary-fixed': 'bg-on-tertiary-fixed',
    'on-tertiary-fixed-variant': 'bg-on-tertiary-fixed-variant',
    'surface-dim': 'bg-surface-dim',
    'surface': 'bg-surface',
    'surface-bright': 'bg-surface-bright',
    'surface-container-lowest': 'bg-surface-container-lowest',
    'surface-container-low': 'bg-surface-container-low',
    'surface-container': 'bg-surface-container',
    'surface-container-high': 'bg-surface-container-high',
    'surface-container-highest': 'bg-surface-container-highest',
    'on-surface': 'bg-on-surface',
    'on-surface-variant': 'bg-on-surface-variant',
    'outline': 'bg-outline',
    'outline-variant': 'bg-outline-variant',
    'inverse-surface': 'bg-inverse-surface',
    'inverse-on-surface': 'bg-inverse-on-surface',
    'inverse-primary': 'bg-inverse-primary',
    'scrim': 'bg-scrim',
    'shadow': 'bg-shadow',
}